version: '3.1'

services:
    mongo:
        image: mongo
        restart: always
        ports:
          - "27017:27017"
        environment: 
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: example
    authentication_service:
        image: authentication_service
        container_name: authentication_service
        restart: always
        ports:
            - "7001:3001"
        depends_on:
            - mongo
        build:
          context: .
          dockerfile: Dockerfile
        command: cargo run
        environment:
          - SECRET_KEY="my-secretkey-to-change-in-prod"
        
